### ISSUE TITLE
Question: Is the fetching done concurrently?

### ISSUE THREAD

**Issue by mscno** [gordalina/hush_gcp_secret_manager#1]
Does this library fetch GCP backed secrets concurrently or one by one?

I have a few apps that depend on 50—100 GCP backed secrets, and I am wondering how startup time is impacted in cases with many secrets?

**Comment by gordalina** [comment]
Secrets are not fetched concurrently, but #6 will address that.

**Comment by gordalina** [comment]
Released in `{:hush, "~>1.0"}`
